# PANDAS 01

NO: 01 - Barkın Gümüş

## Bölüm 1

* `bestsellers` veri kümesini bir DataFrame olarak pandas ile okuyun.  
* Bunu yaptıktan sonra, pandas kullanarak DataFrame'in kaç satır ve kaç sütunu olduğunu bulun.  
* İlk 5 satırı inceleyin.  
* İlk 19 satırı inceleyin.  
* Son 5 satırı inceleyin.  
* Son 2 satırı inceleyin.  
* Hangi sütunlarda (varsa) eksik değerler var?  
* Pandas, "User Rating" sütununa hangi veri tipini atadı?  
* DataFrame'de kaç tane tamsayı (integer) sütunu var?

In [ ]:
import pandas as pd
bestsellers = pd.read_csv("bestsellers.csv")
print(bestsellers.shape)
print(bestsellers.head())

(550, 7)
                                                Name  \
0                      10-Day Green Smoothie Cleanse
1                                  11/22/63: A Novel
2            12 Rules for Life: An Antidote to Chaos
3                             1984 (Signet Classics)
4  5,000 Awesome Facts (About Everything!) (Natio...

                     Author  User Rating  Reviews  Price  Year        Genre
0                  JJ Smith          4.7    17350      8  2016  Non Fiction
1              Stephen King          4.6     2052     22  2011      Fiction
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3             George Orwell          4.7    21424      6  2017      Fiction
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [3]:
print(bestsellers.head(19))

                                                 Name  \
0                       10-Day Green Smoothie Cleanse
1                                   11/22/63: A Novel
2             12 Rules for Life: An Antidote to Chaos
3                              1984 (Signet Classics)
4   5,000 Awesome Facts (About Everything!) (Natio...
5       A Dance with Dragons (A Song of Ice and Fire)
6   A Game of Thrones / A Clash of Kings / A Storm...
7                      A Gentleman in Moscow: A Novel
8       A Higher Loyalty: Truth, Lies, and Leadership
9                           A Man Called Ove: A Novel
10                          A Man Called Ove: A Novel
11  A Patriot's History of the United States: From...
12                            A Stolen Life: A Memoir
13                   A Wrinkle in Time (Time Quintet)
14  Act Like a Lady, Think Like a Man: What Men Re...
15  Adult Coloring Book Designs: Stress Relief Col...
16  Adult Coloring Book: Stress Relieving Animal D...
17     Adult Coloring Book: Stress Relieving Patterns
18  Adult Coloring Books: A Coloring Book for Adul...

                         Author  User Rating  Reviews  Price  Year  \
0                      JJ Smith          4.7    17350      8  2016
1                  Stephen King          4.6     2052     22  2011
2            Jordan B. Peterson          4.7    18979     15  2018
3                 George Orwell          4.7    21424      6  2017
4      National Geographic Kids          4.8     7665     12  2019
5           George R. R. Martin          4.4    12643     11  2011
6           George R. R. Martin          4.7    19735     30  2014
7                   Amor Towles          4.7    19699     15  2017
8                   James Comey          4.7     5983      3  2018
9               Fredrik Backman          4.6    23848      8  2016
10              Fredrik Backman          4.6    23848      8  2017
11             Larry Schweikart          4.6      460      2  2010
12                Jaycee Dugard          4.6     4149     32  2011
13            Madeleine L'Engle          4.5     5153      5  2018
14                 Steve Harvey          4.6     5013     17  2009
15  Adult Coloring Book Designs          4.5     2313      4  2016
16           Blue Star Coloring          4.6     2925      6  2015
17           Blue Star Coloring          4.4     2951      6  2015
18    Coloring Books for Adults          4.5     2426      8  2015

          Genre
0   Non Fiction
1       Fiction
2   Non Fiction
3       Fiction
4   Non Fiction
5       Fiction
6       Fiction
7       Fiction
8   Non Fiction
9       Fiction
10      Fiction
11  Non Fiction
12  Non Fiction
13      Fiction
14  Non Fiction
15  Non Fiction
16  Non Fiction
17  Non Fiction
18  Non Fiction

In [ ]:
bestsellers.tail()

,Name,Author,User Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [ ]:
bestsellers.tail(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [10]:
print(bestsellers.isnull().sum())

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [9]:
print(bestsellers['User Rating'].dtype)

float64

In [13]:
print(bestsellers.dtypes)
print("Integer sütun sayısı:", bestsellers.select_dtypes(include='int').shape[1])

Name               str
Author             str
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre              str
dtype: object
Integer sütun sayısı: 3

## Bölüm 2

* `mount_everest_deaths` veri kümesinin kendi indeks sütunu vardır. Veriyi içe aktarırken bu mevcut indeks sütununu kullanın.  
* Hangi sütunlarda sıfır eksik değer (null) vardır?  
* Hangi sütunda en fazla eksik değer (null) var?

In [11]:
everest = pd.read_csv("mount_everest_deaths.csv", index_col=0)
nulls = everest.isnull().sum()
print(nulls)
print("Eksik değeri olmayan sütunlar:", list(nulls[nulls == 0].index))
print("En fazla eksik değere sahip sütun:", nulls.idxmax())

Name                0
Date                0
Age               150
Expedition         39
Nationality         1
Cause of death     14
Location           19
dtype: int64
Eksik değeri olmayan sütunlar: ['Name', 'Date']
En fazla eksik değere sahip sütun: Age

## Bölüm 3

* `movie_titles.tsv` veri kümesini içe aktarın.  
* Bu veri kümesinin virgül ile ayrılmadığını fark edeceksiniz! `read_csv` fonksiyonuna ayırıcıyı belirtmeniz gerekecek.  
* Veri kümesi sütun başlıkları ile gelmiyor, bu yüzden başlıkları sizin sağlamanız gerekiyor. Sütunlar sırasıyla şunlardır: `id`, `title`, `year`, `imdb_rating`, `imdb_id`, ve `genres`  
* Veri kümesini başarıyla DataFrame'e aktardıktan sonra, son 7 satırı inceleyin!

In [12]:
movies = pd.read_csv(
    "movie_titles.tsv",
    sep="\t",
    header=None,
    names=["id", "title", "year", "imdb_rating", "imdb_id", "genres"],
)
movies.tail(7)

,id,title,year,imdb_rating,imdb_id,genres
610,m610,the wizard of oz,1939,8.3,104873.0,['adventure' 'family' 'fantasy' 'musical']
611,m611,the world is not enough,1999,6.3,60047.0,['action' 'adventure' 'thriller']
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']